url: "https://www.goktugocal.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
# title: 'goktugocal'

# Setup
title:            goktugocal
tagline:          'Göktuğ Öcal'
email:            'goktugocal41@gmail.com'
description:      "Göktuğ Öcal's Personal Website, basically the things that I want to talk about. Data Science posts, projects that I made, things that I love to learn and describe to you. Movies reviews that I love, and more."
website:          https://www.goktugocal.com/
github_username:  'goktugocal'
linkedin_username: 'goktugocal'
instagram_username: 'goktug.ocal'

author:
  name:           'Göktuğ Öcal'
  url:            https://www.goktugocal.com/

image: "/assets/img/favicon.png"

plugins:
  - jekyll-target-blank
  - jekyll-seo-tag
  - jekyll-sitemap

values:
  mathjax: true