url: "https://www.goktugocal.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
# title: 'goktugocal'

# Setup
title:            goktugocal
tagline:          'Göktuğ Öcal'
email:            'goktugocal41@gmail.com'
description:      "Goktug Ocal's Personal Website. Data Science Engineering Movies and more."
website:          https://www.goktugocal.com/
github_username:  'goktugocal'
twitter_username: 'mrshovvtime'
linkedin_username: 'goktugocal'
instagram_username: 'goktug.ocal'

author:
  name:           'Göktuğ Öcal'
  url:            https://www.goktugocal.com/

image: "/assets/img/favicon.png"

plugins:
  - jekyll-target-blank
  - jekyll-seo-tag
  - jekyll-sitemap